"""add climbing tables crag area route ascent

Revision ID: 859251e032bc
Revises: 5f7f246f9479
Create Date: 2026-03-15 13:19:19.966682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '859251e032bc'
down_revision: Union[str, Sequence[str], None] = '5f7f246f9479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('venue_type', sa.Enum('outdoor_crag', 'indoor_gym', name='venuetype'), nullable=False),
    sa.Column('default_grade_sys', sa.Enum('french', 'yds', 'v_scale', 'uiaa', 'font', name='gradesystem'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crag_name'), 'crag', ['name'], unique=False)
    op.create_index(op.f('ix_crag_name_normalized'), 'crag', ['name_normalized'], unique=False)
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crag_id'], ['crag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_name_normalized'), 'area', ['name_normalized'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_system', sa.Enum('french', 'yds', 'v_scale', 'uiaa', 'font', name='gradesystem'), nullable=False),
    sa.Column('style', sa.Enum('sport', 'trad', 'boulder', 'multi_pitch', 'alpine', name='routestyle'), nullable=False),
    sa.Column('pitches', sa.Integer(), nullable=False),
    sa.Column('height_m', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crag_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['crag_id'], ['crag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_name_normalized'), 'route', ['name_normalized'], unique=False)
    op.create_table('ascent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tick_type', sa.Enum('onsight', 'flash', 'redpoint', 'pinkpoint', 'repeat', 'attempt', 'hang', name='ticktype'), nullable=False),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('crag_id', sa.Integer(), nullable=False),
    sa.Column('crag_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('route_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crag_id'], ['crag.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ascent_crag_tick_date', 'ascent', ['crag_id', 'tick_type', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ascent_crag_tick_date', table_name='ascent')
    op.drop_table('ascent')
    op.drop_index(op.f('ix_route_name_normalized'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_area_name_normalized'), table_name='area')
    op.drop_table('area')
    op.drop_index(op.f('ix_crag_name_normalized'), table_name='crag')
    op.drop_index(op.f('ix_crag_name'), table_name='crag')
    op.drop_table('crag')
    # ### end Alembic commands ###
