"""add endurance_activity table

Revision ID: a25ec3f6c41d
Revises: 859251e032bc
Create Date: 2026-03-15 14:29:20.709476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a25ec3f6c41d'
down_revision: Union[str, Sequence[str], None] = '859251e032bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endurance_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervals_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('intervals_icu', 'manual', name='activitysource'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_endurance_activity_date', 'endurance_activity', ['date'], unique=False)
    op.create_index('ix_endurance_activity_intervals_id', 'endurance_activity', ['intervals_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_endurance_activity_intervals_id', table_name='endurance_activity')
    op.drop_index('ix_endurance_activity_date', table_name='endurance_activity')
    op.drop_table('endurance_activity')
    # ### end Alembic commands ###
